name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Hello
      run: |
        cd cd-ci-pipeline && make hello
    
    - name: Install Dependencies
      run: |
        cd cd-ci-pipeline && make install
    
    - name: lint with pylint
      run: |
        cd cd-ci-pipeline && make lint
    - name: test with pytest
      run: |
        cd cd-ci-pipeline && make test
    - name: Format Code
      run: |
        cd cd-ci-pipeline && make format
